"""
Stubs for gmpy2, copied from tno.mpc.encryption_schemes.utils.

We make gmpy2.mpz a subclass of int in the stubs, but in practice it is a virtual subclass of `numbers.Integral`.
However, static type checkers cannot process dynamically assigned types, so this is a workaround for static type
checkers.

NOTE: When checking for mpz objects and built-in integers in code, use `isinstance(obj, numbers.Integral)`, but
if parameters are passed between functions that can be either mpz objects or built-in integers, use the `int` type.
This works, because mpz objects act like integers.
"""

from __future__ import annotations

class mpz(int): ...

def from_binary(b: bytes) -> mpz: ...
def invert(x: int, m: int) -> mpz: ...
def is_prime(x: int, n: int = ...) -> bool: ...
def lcm(a: int, b: int) -> mpz: ...
def next_prime(x: int) -> mpz: ...
def powmod(a: int, e: int, p: int) -> mpz: ...
def to_binary(a: mpz) -> bytes: ...
